### ISSUE TITLE
Should check AV before receipting

### ISSUE THREAD

**Issue by necrophonic** [ONSdigital/sdx-seft-consumer-service#57]
Currently sends receipt before checking the file through the AV service. This means that if the AV service is unavailable the receipt gets sent and the file re-queued, causing multiple receipts to be sent whilst waiting for the service to become available.

In `app/main.py` ~ line 109:

```python
...
  payload = self.extract_file(decrypted_payload, tx_id)
  self.bound_logger = self.bound_logger.bind(case_id=payload.case_id, survey_id=payload.survey_id)
  self._send_receipt(payload.case_id, tx_id)

  if settings.ANTI_VIRUS_ENABLED:
      av_check = AntiVirusCheck(tx_id=tx_id)
      av_check.send_for_av_scan(payload)
...
```

**Comment by pricem14pc** [comment]
In principle, sending the receipt before checking the file is fine. The receipting is confirmation that we have received the file from the respondent so this should happen as close to the upload as possible. Having it as part of the flow that does the scan result (re)requests is the issue.

**Comment by insacuri** [comment]
Closing because this service doesn't receipt anymore
